#!/bin/bash
VM=${PYTHON:-python3}
PW_PATH=$(dirname $(realpath $0))
NEW_PYTHONPATH=${PW_PATH}:${PYTHONPATH}

if [ -z "$*" ]; then
    # run the interactive Command Line Interface (CLI)
	PYTHONPATH=${NEW_PYTHONPATH} ${VM} ${PW_PATH}/packetweaver/pw.py interactive
else
    # run the CLI with the provided parameters
    PYTHONPATH=${NEW_PYTHONPATH} ${VM} ${PW_PATH}/packetweaver/pw.py $@
fi
